Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
   Exclude:
     - "spec/support/json_output_formatter.rb"
Metrics/MethodLength:
   Exclude:
     - "spec/support/json_output_formatter.rb"
